### ISSUE TITLE
Request for more icons

### ISSUE THREAD

**Issue by sergiks** [get-icon/geticon#3]
Please add icons for the following products, if possible:

* [Swoole](https://www.swoole.co.uk/)
* [FFMPEG](https://ffmpeg.org/)
* Linux
* Amazon Web Services and specific products like S3, CloudFrone, EC2, SES, etc.
* Adobe AfterEffects, Premiere Pro, Lightroom

**Comment by tomchen** [comment]
OK I'll add those when I make the planned overhaul of the repo #6

**Comment by tomchen** [comment]
Per request,

Added:
- Swoole
- FFMPEG
- many Adobe product icons

Already exist, modified / updated to the latest icons, added more aliases:
- Linux
- AWS products
- Adobe products
